server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:mydatabasename;DB_CLOSE_DELAY=-1;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    url: jdbc:h2:mem:mydatabasename;DB_CLOSE_DELAY=-1;
    user: sa
    password:
    locations: filesystem:src/main/resources/db/migration
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        trace: false
        web-allow-others: false
